version: '3.6'
services:
  explorer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3080"
    restart: always
    command: ["npm", "run", "start"]
    environment:
      NODE_ENV: "development"
      PORT: "3000"
      NEXT_PUBLIC_CHAIN_TYPE: "testnet"
      NEXT_PUBLIC_GRAPHQL_URL: "http://host.docker.internal:8080/v1/graphql"
      NEXT_PUBLIC_GRAPHQL_WS: "ws://host.docker.internal:8080/v1/graphql"
      NEXT_PUBLIC_URL: "http://localhost:3000"
      NEXT_PUBLIC_RPC_WEBSOCKET: "http://143.198.11.84:26657/websocket"
      REACT_APP_ENVIRONMENT: "PROD"
