apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vars
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_PUBLIC_CHAIN_TYPE: "testnet"
  NEXT_PUBLIC_GRAPHQL_URL: "https://hasura.k8s.stage.realio.fund/v1/graphql"
  NEXT_PUBLIC_GRAPHQL_WS: "wss://hasura.k8s.stage.realio.fund/v1/graphql"
  NEXT_PUBLIC_RPC_WEBSOCKET: "ws://143.198.11.84:26657/websocket"
  REACT_APP_ENVIRONMENT: "PROD"